---
  hosts: rails
  become: true
  name: 'Install Ruby&Rails environment'

  tasks:

    - name: 'Update repositories cache'
      apt:
        update_cache: yes

    - name: 'Install prerequisites packages'
      apt:
        name: 
          - autoconf 
          - bison 
          - build-essential 
          - libssl-dev 
          - libyaml-dev 
          - libreadline6-dev 
          - zlib1g-dev 
          - libncurses5-dev 
          - libffi-dev 
          - libgdbm5 
          - libgdbm-dev 
          - git
        state: present

    - name: 'Clone rbenv repository'
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: ~/.rbenv

    - name: 'Add rbenv config un bashrc'
      blockinfile:
        path: ~/.bashrc
        block: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"

    - name: 'Source bashrc'
      shell: . /home/{{ ansible_user }}/.bashrc

    - name: 'Clone ruby-build repo'
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: ~/.rbenv/plugins/ruby-build

    - name: 'Install ruby'
      remote_user: "{{ ansible_user }}"
      rbenv:
        version: 2.5.3
        rbenv_root: /home/{{ ansible_user }}/.rbenv

    - name: 'Set global version for rbenv'
      remote_user: "{{ ansible_user }}"
      rbenv:
        subcommand: global
        version: 2.5.3
        rbenv_root: /home/{{ ansible_user }}/.rbenv

    - name: 'Install bundler'
      gem:
        name: bundler
        state: present
        executable: /home/{{ ansible_user }}/.rbenv/shims/gem
      # become: yes

    - name: 'Install rails'
      gem:
        name: rails
        version: 5.2.0
        state: present
