---
- hosts: rails
  roles: 
    - suzuki-shunsuke.rbenv-module
  vars:
    - rbenv_root: /home/{{ ansible_user }}/.rbenv
    - user: "{{ ansible_user }}"
  name: 'Install Ruby&Rails environment'

  tasks:

    - name: 'Update repositories cache'
      apt:
        update_cache: yes
      become: true

    - name: 'Install prerequisites packages'
      apt:
        name: 
          - autoconf 
          - bison 
          - build-essential 
          - libssl-dev 
          - libyaml-dev 
          - libreadline6-dev 
          - zlib1g-dev 
          - libncurses5-dev 
          - libffi-dev 
          - libgdbm5 
          - libgdbm-dev 
          - git
        state: present
      become: true


    - name: 'Clone rbenv repository'
      git:
        repo: https://github.com/rbenv/rbenv.git
        dest: /home/{{ ansible_user }}/.rbenv

    - name: 'Add rbenv config un bashrc'
      blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        block: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"

    - name: 'Clone ruby-build repo'
      git:
        repo: https://github.com/rbenv/ruby-build.git
        dest: /home/{{ ansible_user }}/.rbenv/plugins/ruby-build

    - name: 'Install ruby'
      rbenv:
        subcommand: install
        version: 2.5.3
        rbenv_root: "{{ rbenv_root }}"
        
    - name: 'Set global version for rbenv'
      remote_user: "{{ ansible_user }}"
      rbenv:
        subcommand: global
        version: 2.5.3
        rbenv_root: /home/{{ ansible_user }}/.rbenv

    - name: 'Add rbinstall alias'
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: alias rbinstall='rbenv local $(cat .ruby-version) || rbenv install $(cat .ruby-version) && rbenv local $(cat .ruby-version)'

    - name: 'Source bashrc'
      shell: . /home/{{ ansible_user }}/.bashrc
      
    - name: 'Configure gem'
      lineinfile:
        path: /home/{{ ansible_user }}/.gemrc
        line: 'gem: --no-document'
        create: yes

    - name: 'Install bundler'
      shell: gem install bundler

    - name: 'Install rails'
      shell: gem install rails
